- name: swap 비활성화
  command: swapoff -a
  changed_when: false

- name: 재부팅 후 swqp 비활성화
  replace:
    path: /etc/fstab
    regexp: '^(\s*)(/dev/.*?\sswap\s+swap\s+.*)$'
    replace: '#\2'

- name: SELinux 비활성화
  selinux:
    state: disabled

- name: 방화벽 비활성화
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: yes

- name: 필수 패키지 설치
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - curl
      - wget
    state: present

- name: 브리지 네트워크 설정 및 모듈 로드
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Set kernel parameters for Kubernetes
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    reload: yes
  loop:
    - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { key: 'net.ipv4.ip_forward', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }

- name: kubernets 저장소 추가
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes

- name: kubernets 패키지 설치
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    disable_excludes: kubernetes

- name: kubelet 서비스 활성화
  systemd:
    name: kubelet
    enabled: yes
    state: started
