- name: Join worker node to cluster
  command: "{{ hostvars[groups['master'][0]]['join_command'] }}"
  args:
    creates: /etc/kubernetes/kubelet.conf

- name: 클러스터에 워커 노드 조인
  shell: "{{ join_command }}"
  register: join_result
  when: node_joined_check.rc != 0

- name: 조인 결과 출력
  debug:
    var: join_result.stdout_lines
  when: join_result is defined and join_result.changed

- name: kubelet 서비스 시작 및 활성화
  systemd:
    name: kubelet
    state: started
    enabled: yes

- name: 워커 노드가 Ready 상태가 될 때까지 대기
  shell: kubectl get nodes {{ ansible_hostname }} --kubeconfig=/etc/kubernetes/kubelet.conf -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}'
  register: worker_ready_status
  until: worker_ready_status.stdout == "True"
  retries: 20
  delay: 15
  when: node_joined_check.rc != 0

- name: 워커 노드 상태 확인
  shell: kubectl get nodes {{ ansible_hostname }} --kubeconfig=/etc/kubernetes/kubelet.conf
  register: worker_status
  when: node_joined_check.rc != 0

- name: 워커 노드 상태 출력
  debug:
    var: worker_status.stdout_lines
  when: worker_status is defined