---
- name: 기존 클러스터 상태 확인
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_config

- name: 기존 클러스터가 있다면 초기화 (멱등성 보장)
  ansible.builtin.command: kubeadm reset -f
  when: kubeadm_config.stat.exists

- name: kubeadm 설정 파일 생성 및 클러스터 초기화
  block:
    - name: kubeadm 설정 파일 템플릿 복사
      ansible.builtin.template:
        src: kubeadm-config.j2
        dest: /tmp/kubeadm-config.yaml
        
    - name: kubeadm init 실행 (설정 파일 사용)
      ansible.builtin.command: kubeadm init --config /tmp/kubeadm-config.yaml --upload-certs
      register: kubeadm_init_result
      changed_when: true

- name: kubeadm init이 완료되고 admin.conf 파일이 생성될 때까지 대기
  ansible.builtin.wait_for:
    path: /etc/kubernetes/admin.conf
    state: present
    timeout: 300
    delay: 10  

- name: ubuntu 사용자가 kubectl을 사용할 수 있도록 설정
  block:
    - name: /home/ubuntu/.kube 디렉터리 생성
      ansible.builtin.file:
        path: "/home/ubuntu/.kube"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: 관리자용 admin.conf 파일을 ubuntu 사용자 홈으로 복사
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: '0600'

- name: Calico 네트워크 애드온 설치
  become: no # ubuntu 사용자로 kubectl 실행
  ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  changed_when: false

- name: 클러스터 조인 명령어 생성
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command_result
  changed_when: false

# - name: [디버깅] 생성된 조인 명령어 확인
#   ansible.builtin.debug:
#     msg: "워커 노드 조인 명령어: {{ join_command_result.stdout }}"

- name: 조인 명령어를 모든 호스트가 공유하도록 설정 (delegate_to 사용)
  ansible.builtin.set_fact:
    join_command: "{{ join_command_result.stdout }}"
  delegate_to: localhost
  delegate_facts: true